yarnPath: ".yarn/releases/yarn-berry.cjs"
nodeLinker: node-modules
packageExtensions:
  reason-react@*:
    peerDependencies:
      bs-platform: "*"
      react: "*"
      react-dom: "*"
    dependencies:
      bs-platform: "*"
      react: "*"
      react-dom: "*"
